### PR TITLE
Fix Scorecard Test

### LINKED ISSUE #684: Fix Scorecard Test
The scorecard test is currently failing, and it's preventing us from proceeding with the testing process. We need to address this issue to ensure the successful execution of all scorecard tests.

### PR DESCRIPTION
**Pull request by Msarawan**

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -0,0 +1,59 @@
+#!/usr/bin/env bash
```
Comment (gaohoward) [inline install.sh:1]: @Msarawan I think the name of the script should be more specific, like "install_olm.sh" so that it would be easy to get the idea what this script is about. Also the script is better to be moved into the **hack** dir.

**Review by gaohoward — CHANGES_REQUESTED** [review]

File: install.sh (hunk 1 above)
Comment (Msarawan) [reply install.sh]: modified the changes.

**Review by brusdev — APPROVED** [review]
@Msarawan nice work!

**Comment by Msarawan** [comment]
> @Msarawan nice work!

Thank You! @brusdev

**Review by gaohoward — APPROVED** [review]
