### PR TITLE
[#353] Adding credential secret tests

### LINKED ISSUE #353: Adding credential secret tests
**Describe the bug**

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by gaohoward**
some tests regarding the handling of credential secret

### CODE REVIEW

File: controllers/activemqartemis_controller_test.go [hunk 1]
```diff
@@ -122,6 +122,236 @@ var _ = Describe("artemis controller", func() {
...
+
+			// cleanup
+			Expect(k8sClient.Delete(ctx, brokerCr)).Should(Succeed())
+			By("check it has gone")
+			Eventually(func() bool {
+				return checkCrdDeleted(brokerCr.Name, defaultNamespace, createdBrokerCr)
+			}, timeout, interval).Should(BeTrue())
+		})
+
+		It("user credential secret", func() {
```
Comment (gtully) [inline controllers/activemqartemis_controller_test.go:195]: my suspicion is that in this test there are errors in the logs, b/c we track this secret and try and create it, but it will already exist.

**Review by gtully — COMMENTED** [review]
great additions

File: controllers/activemqartemis_controller_test.go [hunk 2]
```diff
@@ -122,6 +122,236 @@ var _ = Describe("artemis controller", func() {
 		}
 	})
 
+	Context("broker resource tracking", Label("broker-resource-tracking-context"), func() {
+		It("default user credential secret", func() {
+			By("deploy a broker")
+			brokerCr, createdBrokerCr := DeployCustomBroker(defaultNamespace, nil)
```
Comment (brusdev) [inline controllers/activemqartemis_controller_test.go:128]: Could we set custom `adminUser` and `adminPassword` to check their values in the credential secret created by the operator?

File: controllers/activemqartemis_controller_test.go [hunk 3]
```diff
@@ -122,6 +122,236 @@ var _ = Describe("artemis controller", func() {
...
+
+			By("deploy a user credential secret")
+			secret, createdSecret := DeploySecret(defaultNamespace, func(candidate *corev1.Secret) {
+				candidate.Name = userSecretName
+				candidate.StringData = secretData
+			})
+
+			By("deploy a broker")
+			brokerCr, createdBrokerCr := DeployCustomBroker(defaultNamespace, func(candidate *brokerv1beta1.ActiveMQArtemis) {
+				candidate.Name = brokerCrName
```
Comment (brusdev) [inline controllers/activemqartemis_controller_test.go:212]: Could we set custom `adminUser` and `adminPassword` to check their values in the credential secret updated by the operator?
I guess the test should fail because the secret isn't owned by the operator but it used to work in previous versions.

File: controllers/activemqartemis_controller_test.go (hunk 2 above)
Comment (gaohoward) [reply controllers/activemqartemis_controller_test.go:128]: yes that deserves another test.

File: controllers/activemqartemis_controller_test.go (hunk 3 above)
Comment (gaohoward) [reply controllers/activemqartemis_controller_test.go:212]: yes I'll add one test. But yes we would expect the secret not to get updated. (I'll test it as such as it is current behavior). We can update it if we decide to do otherwise.

File: controllers/activemqartemis_controller_test.go (hunk 1 above)
Comment (gaohoward) [reply controllers/activemqartemis_controller_test.go:271]: it is true.

File: controllers/activemqartemis_reconciler.go [hunk 4]
```diff
@@ -476,10 +479,20 @@ func (reconciler *ActiveMQArtemisReconcilerImpl) sourceEnvVarFromSecret(fcustomR
 				}
 			}
 		}
+		//if operator doesn't own it, don't track
+		if len(secretDefinition.OwnerReferences) > 0 {
+			for _, or := range secretDefinition.OwnerReferences {
+				if or.Kind == "ActiveMQArtemis" && or.Name == customResource.Name {
```
Comment (gtully) [inline controllers/activemqartemis_reconciler.go:485]: Is that "ActiveMQArtemis" constant defined somewhere else that we can reference?

File: controllers/activemqartemis_controller_test.go [hunk 5]
```diff
@@ -4267,6 +4744,54 @@ var _ = Describe("artemis controller", func() {
...
+				"AMQ_PASSWORD":         "admin",
+				"AMQ_CLUSTER_USER":     "admin",
+				"AMQ_CLUSTER_PASSWORD": "admin",
+			},
+		}
+
+		By("Deploying credentialsSecret")
+		Expect(k8sClient.Create(ctx, &credentialsSecret)).Should(Succeed())
+
+		StartCapturingLog()
```
Comment (gtully) [inline controllers/activemqartemis_controller_test.go:4773]: great addition

File: controllers/activemqartemis_reconciler.go (hunk 4 above)
Comment (gaohoward) [reply controllers/activemqartemis_reconciler.go:485]: Yeah it should, let me find.

Comment (gaohoward) [reply controllers/activemqartemis_reconciler.go:485]: Didn't find existing one. I added a var to suite_test.go.
