### PR TITLE
[#499] Allow SSL secret to be reused in the CR

### LINKED ISSUE #499: Allow SSL secret to be reused in the CR
**Describe the bug**
It's a common case to use only one certificate for all exposed endpoints by the broker.

For example, when applying a new Custom Resource and exposing the console using SSL, if you want to use the same certificate for both acceptor and the console, you need to create different secrets.

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by gaohoward**

### CODE REVIEW

File: controllers/activemqartemis_reconciler.go [hunk 1]
```diff
@@ -1514,15 +1549,24 @@ func MakeVolumes(customResource *brokerv1beta1.ActiveMQArtemis, namer Namers) []
...
 	}
 
 	if customResource.Spec.Console.SSLEnabled {
 		clog.V(1).Info("Make volumes for ssl console exposure on k8s")
 		secretName := namer.SecretsConsoleNameBuilder.Name()
-		volume := volumes.MakeVolume(secretName)
-		volumeDefinitions = append(volumeDefinitions, volume)
+		if "" != customResource.Spec.Console.SSLSecret {
+			secretName = customResource.Spec.Console.SSLSecret
+		}
```
Comment (brusdev) [inline controllers/activemqartemis_reconciler.go:1564]: How is this related to #499?

File: controllers/activemqartemis_controller_test.go [hunk 2]
```diff
@@ -126,6 +126,266 @@ var _ = Describe("artemis controller", func() {
...
+					Name:      serviceName,
+					Namespace: defaultNamespace,
+				}
+				Eventually(func(g Gomega) {
+					g.Expect(k8sClient.Get(ctx, serviceKey, &service)).To(Succeed())
+				}, existingClusterTimeout, existingClusterInterval).Should(Succeed())
+
+				if isOpenshift {
+
+					By("check route is created for console")
```
Comment (brusdev) [inline controllers/activemqartemis_controller_test.go:271]: We could just validate that the pod is ready, why do we need to validate ingress or route resources?

File: controllers/activemqartemis_reconciler.go [hunk 3]
```diff
@@ -1262,6 +1259,40 @@ func (reconciler *ActiveMQArtemisReconcilerImpl) ProcessResources(customResource
...
+
+		if !reflect.DeepEqual(deployedRoute.Spec.TLS, requestedRoute.Spec.TLS) {
+			reqLogger.V(1).Info("Route tls not equal", "deployed", deployedRoute.Spec.TLS, "requested", requestedRoute.Spec.TLS)
+			return false
+		}
+		reqLogger.V(1).Info("routes are equal")
+		return true
+	})
+
```
[the remark this answers is not in the document]
Comment (gaohoward) [reply controllers/activemqartemis_reconciler.go:1295]: This is to improve reconcile of route resources. The route has some other fields that are auto filled by the openshift, next time when it reconcile again the "deployed" route will be "different" from the expected route object, causing unnecessary resource updates. (I think the same is true with ingress, which is why we added a comparator for ingress too).

File: controllers/activemqartemis_reconciler.go [hunk 4]
```diff
@@ -1501,8 +1533,11 @@ func MakeVolumes(customResource *brokerv1beta1.ActiveMQArtemis, namer Namers) []
 		if "" != acceptor.SSLSecret {
 			secretName = acceptor.SSLSecret
 		}
-		volume := volumes.MakeVolume(secretName)
-		volumeDefinitions = append(volumeDefinitions, volume)
+		if _, ok := secretVolumes[secretName]; !ok {
+			volume := volumes.MakeVolume(secretName)
+			volumeDefinitions = append(volumeDefinitions, volume)
+			secretVolumes[secretName] = secretName
+		}
```
[the remark this answers is not in the document]
Comment (gaohoward) [reply controllers/activemqartemis_reconciler.go:1540]: yeah tha't a good idea , will do.

File: controllers/activemqartemis_reconciler.go (hunk 1 above)
Comment (gaohoward) [reply controllers/activemqartemis_reconciler.go:1564]: I believe this is a bug (it should have been there, otherwise the user specified secret will be ignored).

File: controllers/activemqartemis_controller_test.go (hunk 2 above)
Comment (gaohoward) [reply controllers/activemqartemis_controller_test.go:271]: I do think that's necessary to check further the ingress or routes are created. Pod is ready only means pod is up it doesn't mean we fixed the shared secret problem.

File: controllers/activemqartemis_reconciler.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (brusdev) [reply controllers/activemqartemis_reconciler.go:1295]: Ingress comparator was added because the default comparator doesn't include it while it already includes a comparator for Route, for further details see https://github.com/RHsyseng/operator-utils/blob/v1.4.10/pkg/resource/compare/defaults.go#L98

I see the test `console and acceptor share one secret` passing also without this comparator.

The default Route comparator seems similar to the one added, what does the custom comparator do that the default doesn't?

File: pkg/resources/k8s_actions.go [hunk 5]
```diff
@@ -109,7 +109,8 @@ func Update(client client.Client, clientObject client.Object) error {
 				// "StatefulSet.apps is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden"}
 				reqLogger.V(1).Info("Deleting on failed updating "+objectTypeString, "obj", clientObject, "Forbidden", err)
 				err = Delete(client, clientObject)
-				break
+			} else {
+				reqLogger.Error(err, "Got status error")
 			}
```
Comment (brusdev) [inline pkg/resources/k8s_actions.go:114]: I see the test `console and acceptor share one secret` passing also without this change, why is this change required?

Comment (gaohoward) [reply pkg/resources/k8s_actions.go:114]: It's a mistake in the code. I corrected it.

**Review by brusdev — APPROVED** [review]
