### PR TITLE
Fix operator error on kubernetes

### LINKED ISSUE #28: Operator can't read RouteList on K8s
**Describe the bug**
As kubernetes doesn't recognize Route resources the operator gets failure when
reading RouteList from it. It gives the following error:

2020-11-02T14:04:01.196Z	ERROR	controller_v2alpha3activemqartemis	Failed to list deployed objects. 	{"error": "no matches for kind \"Route\" in version \"route.openshift.io/v1\""}

**To Reproduce**
1. build operator
2. deploy operator in kubernetes
3. check the operator pod's log

**Platform (please complete the following information):**
 - OS: linux
 - Go [e.g. 1.13.4

**Expected behavior**
there should be no such error in the logs

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by gaohoward**
The reconciler tries to read RouteList on both openshift and
kubernetes but kubernetes doesn't recognize Route resource.

### CODE REVIEW

File: pkg/controller/broker/v2alpha3/activemqartemis/activemqartemis_reconciler.go [hunk 1]
```diff
@@ -1227,16 +1227,28 @@ func getDeployedResources(instance *brokerv2alpha3.ActiveMQArtemis, client clien
...
-	)
+	var resourceMap map[reflect.Type][]resource.KubernetesResource
+	var err error
+	if isOpenshift, _ := environments.DetectOpenshift(); isOpenshift {
+		resourceMap, err = reader.ListAll(
+			&corev1.PersistentVolumeClaimList{},
+			&corev1.ServiceList{},
+			&appsv1.StatefulSetList{},
+			&routev1.RouteList{},
+			&extv1b1.IngressList{},
```
Comment (brusdev) [inline pkg/controller/broker/v2alpha3/activemqartemis/activemqartemis_reconciler.go:1238]: I added `&extv1b1.IngressList{},` for Kubernetes, maybe after this split we could remove it from the OpenShift branch

Comment (gaohoward) [reply pkg/controller/broker/v2alpha3/activemqartemis/activemqartemis_reconciler.go:1238]: right, will remove that. Thanks!
