### PR TITLE
[#964] Skip ingress openshift test in non-openshift environment

### LINKED ISSUE #964: Ingress should be tracked in Openshift case
**Describe the bug**
Now we allow exposing ingress mode (such as for acceptors) the Ingress should be tracked.

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

### PR DESCRIPTION
**Pull request by gaohoward**

### CODE REVIEW

File: controllers/activemqartemis_controller_test.go [hunk 1]
```diff
@@ -5314,7 +5314,9 @@ var _ = Describe("artemis controller", func() {
 		})
 
 		It("with ingress in openshift", Label("with-ing-in-openshift"), func() {
-			if os.Getenv("USE_EXISTING_CLUSTER") == "true" {
+			if os.Getenv("USE_EXISTING_CLUSTER") != "true" || !isOpenshift {
+				Skip("Existing OpenShift cluster required")
+			} else {
```
Comment (brusdev) [inline controllers/activemqartemis_controller_test.go:5319]: The else could be removed because Skip function ends the test

**Comment by brusdev** [comment]
Could you replace `[NO-ISSUE]` with `[#964]` in the commit message?

**Review by brusdev — APPROVED** [review]
