### PR TITLE
Issue #143  Seeing repeated logs in operator pod "Waited for 1.645288…

### LINKED ISSUE #143: Seeing repeated logs in operator pod "Waited for 1.645288647s due to client-side throttling...."
**Describe the bug**
When deploying operator using main branch, there are lots of repeated messages like:

I0209 05:03:58.887360       1 request.go:665] Waited for 1.443738214s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/storage.k8s.io/v1beta1?timeout=32s
I0209 05:04:08.936364       1 request.go:665] Waited for 1.498454731s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/broker.amq.io/v2alpha1?timeout=32s
I0209 05:04:18.937437       1 request.go:665] Waited for 1.494724975s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/networking.k8s.io/v1?timeout=32s
I0209 05:04:28.986070       1 request.go:665] Waited for 1.544419551s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/broker.amq.io/v2alpha5?timeout=32s
I0209 05:04:39.036038       1 request.go:665] Waited for 1.594793707s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/scheduling.k8s.io/v1?timeout=32s
I0209 05:04:49.036454       1 request.go:665] Waited for 1.595080939s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/policy/v1beta1?timeout=32s
I0209 05:04:59.037772       1 request.go:665] Waited for 1.596584129s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
I0209 05:05:09.086501       1 request.go:665] Waited for 1.645288647s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/policy/v1?timeout=32s

**To Reproduce**
1. deploy the operator in k8s and you will see the logs.

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by gaohoward**
…647s due to client-side throttling...."

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -185,7 +185,7 @@ func main() {
 	if err != nil {
 		log.Error(err, "failed to start the background process to auto-detect the operator capabilities")
 	} else {
-		autodetect.Start()
+		autodetect.DetectOpenshift()
```
Comment (gtully) [inline main.go:188]: I guess we need to check for err, and repeat in some sort of loop with backoff in the event that the detection fails for some reason.  Log if there is a problem, sleep and retry. In general the env should be available, but just in case.

File: pkg/utils/common/auto_detect.go [hunk 2]
```diff
@@ -16,77 +16,39 @@ limitations under the License.
...
-
-func (b *Background) detectOpenshift() {
+func (b *AutoDetector) DetectOpenshift() (bool, error) {
 	apiGroupVersion := "operator.openshift.io/v1"
 	kind := OpenShiftAPIServerKind
 	stateManager := GetStateManager()
-	isOpenshift, _ := ResourceExists(b.dc, apiGroupVersion, kind)
+	isOpenshift, err := ResourceExists(b.dc, apiGroupVersion, kind)
+	if err != nil {
+		return false, err
```
Comment (gtully) [inline pkg/utils/common/auto_detect.go:43]: this is the case the caller needs to be aware of and retry. but this is a lot simpler and a blocking call is sensible for our use case.

**Review by gtully — CHANGES_REQUESTED** [review]

File: main.go (hunk 1 above)
Comment (gaohoward) [reply main.go:188]: will do. thx

File: pkg/utils/common/auto_detect.go (hunk 2 above)
Comment (gaohoward) [reply pkg/utils/common/auto_detect.go:43]: +1

**Comment by gaohoward** [comment]
@gtully Update my PR, pls review again. Thanks!

**Comment by gaohoward** [comment]
@gtully just updated the branch again. pls take a look. thx

File: main.go [hunk 3]
```diff
@@ -185,7 +185,10 @@ func main() {
 	if err != nil {
 		log.Error(err, "failed to start the background process to auto-detect the operator capabilities")
 	} else {
-		autodetect.Start()
+		if err := autodetect.DetectOpenshift(); err != nil {
+			log.Error(err, "failed in detecting openshift")
+			os.Exit(1)
```
Comment (gtully) [inline main.go:190]: this is the correct approach. nice. the controller will restart us and we can try again.

**Review by gtully — APPROVED** [review]
